-- Baseline of the existing mapped schema. Safe for a fresh or matching existing database.
-- UTC conversion and Team C constraints are in the following migration.

CREATE TABLE IF NOT EXISTS public."courses" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" varchar(20) NOT NULL,
    "name" varchar(255) NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk61og8rbqdd2y28rx2et5fdnxd" UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public."users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active" boolean NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "email" varchar(255) NOT NULL,
    "password_hash" varchar(255) NOT NULL,
    "role" varchar(20) NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE (email),
    CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."students" (
    "id" bigint NOT NULL,
    "contact_number" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "preferred_group_size_max" integer,
    "preferred_group_size_min" integer,
    "preferred_study_mode" varchar(20),
    "programme" varchar(255) NOT NULL,
    "school" varchar(255) NOT NULL,
    "year_of_study" integer NOT NULL,
    "target_course_id" bigint,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk7xqmtv7r2eb5axni3jm0a80su" FOREIGN KEY (id) REFERENCES users(id),
    CONSTRAINT "fk8ru5hir964bq979mj0empsc05" FOREIGN KEY (target_course_id) REFERENCES courses(id),
    CONSTRAINT "students_preferred_study_mode_check" CHECK (((preferred_study_mode)::text = ANY ((ARRAY['IN_PERSON'::character varying, 'ONLINE'::character varying, 'EITHER'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."student_courses" (
    "student_id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    PRIMARY KEY ("student_id", "course_id"),
    CONSTRAINT "fksfpq78oyrqua1h0obpl7ulc18" FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT "fkwj1l0mta35u161acdl2tupoo" FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE IF NOT EXISTS public."student_study_goals" (
    "student_id" bigint NOT NULL,
    "study_goal" varchar(30),
    CONSTRAINT "fkafu1idd5ugnqs4csjdsx3jwys" FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT "student_study_goals_study_goal_check" CHECK (((study_goal)::text = ANY ((ARRAY['CONCEPT_REVIEW'::character varying, 'PROBLEM_SOLVING'::character varying, 'EXAM_PREPARATION'::character varying, 'PROJECT_DISCUSSION'::character varying])::text[]))),
    CONSTRAINT "uk85j04c9dphcf0qu7ostunxp86" UNIQUE (student_id, study_goal)
);

CREATE TABLE IF NOT EXISTS public."availability_slots" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "day_of_week" varchar(10) NOT NULL,
    "end_time" time without time zone NOT NULL,
    "start_time" time without time zone NOT NULL,
    "student_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "availability_slots_day_of_week_check" CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[]))),
    CONSTRAINT "fkot1bynbvuijwbpsogo4932g0k" FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE IF NOT EXISTS public."match_requests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "message" varchar(255),
    "responded_at" timestamp without time zone,
    "status" varchar(20) NOT NULL,
    "receiver_id" bigint NOT NULL,
    "sender_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk19vdivd5r3quf2vfjdiiq16pn" FOREIGN KEY (sender_id) REFERENCES students(id),
    CONSTRAINT "fkgfufry38utcw9dwr9vmi22q7a" FOREIGN KEY (receiver_id) REFERENCES students(id),
    CONSTRAINT "match_requests_status_check" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."connections" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "ended_at" timestamp without time zone,
    "student_a_id" bigint NOT NULL,
    "student_b_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk3pnuxs45c3yso3h6s6hrhms73" FOREIGN KEY (student_a_id) REFERENCES students(id),
    CONSTRAINT "fkcs60hjrn3fjsq9y8cksgmy3ve" FOREIGN KEY (student_b_id) REFERENCES students(id)
);

CREATE TABLE IF NOT EXISTS public."study_groups" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active" boolean NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "description" varchar(255),
    "max_group_size" integer NOT NULL,
    "name" varchar(255) NOT NULL,
    "preferred_study_mode" varchar(20),
    "course_id" bigint NOT NULL,
    "leader_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fkllnygr7cgvo5lmjpfx0mmt3mo" FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT "fknxgj6prsr2eosm5628yjhe5lv" FOREIGN KEY (leader_id) REFERENCES students(id),
    CONSTRAINT "study_groups_preferred_study_mode_check" CHECK (((preferred_study_mode)::text = ANY ((ARRAY['IN_PERSON'::character varying, 'ONLINE'::character varying, 'EITHER'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."study_group_goals" (
    "study_group_id" bigint NOT NULL,
    "study_goal" varchar(30),
    CONSTRAINT "fkfyq5csc770fhex2t82sqhym6l" FOREIGN KEY (study_group_id) REFERENCES study_groups(id),
    CONSTRAINT "study_group_goals_study_goal_check" CHECK (((study_goal)::text = ANY ((ARRAY['CONCEPT_REVIEW'::character varying, 'PROBLEM_SOLVING'::character varying, 'EXAM_PREPARATION'::character varying, 'PROJECT_DISCUSSION'::character varying])::text[]))),
    CONSTRAINT "ukp2ar7gb6wnsbtwxtma9tg2s1f" UNIQUE (study_group_id, study_goal)
);

CREATE TABLE IF NOT EXISTS public."group_availability_slots" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "day_of_week" varchar(10) NOT NULL,
    "end_time" time without time zone NOT NULL,
    "start_time" time without time zone NOT NULL,
    "study_group_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk1f2ewt1qbiwnlmyu8o8f2654s" FOREIGN KEY (study_group_id) REFERENCES study_groups(id),
    CONSTRAINT "group_availability_slots_day_of_week_check" CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."group_memberships" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "joined_at" timestamp without time zone NOT NULL,
    "student_id" bigint NOT NULL,
    "study_group_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fkeb90g8qsre212l4d4cfwd1ybk" FOREIGN KEY (study_group_id) REFERENCES study_groups(id),
    CONSTRAINT "fkh1c3rtedq8jbhnww0m6jmcggv" FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT "ukmcb8u7qw3qx77x9bclp499xkn" UNIQUE (study_group_id, student_id)
);

CREATE TABLE IF NOT EXISTS public."group_join_requests" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "message" varchar(255),
    "responded_at" timestamp without time zone,
    "status" varchar(20) NOT NULL,
    "student_id" bigint NOT NULL,
    "study_group_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fke3qlqviqlxk3jwc8sa8qd21o6" FOREIGN KEY (study_group_id) REFERENCES study_groups(id),
    CONSTRAINT "fkg1p1jy88hammuqhmm7lk6jdkr" FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT "group_join_requests_status_check" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."notifications" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp without time zone NOT NULL,
    "message" varchar(255) NOT NULL,
    "read" boolean NOT NULL,
    "type" varchar(40) NOT NULL,
    "recipient_id" bigint NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fkbidwua7j2wct5moxe2q4aar6y" FOREIGN KEY (recipient_id) REFERENCES students(id),
    CONSTRAINT "notifications_type_check" CHECK (((type)::text = ANY ((ARRAY['MATCH_REQUEST_RECEIVED'::character varying, 'MATCH_REQUEST_ACCEPTED'::character varying, 'MATCH_REQUEST_DECLINED'::character varying, 'CONNECTION_ENDED'::character varying, 'GROUP_JOIN_REQUEST_RECEIVED'::character varying, 'GROUP_JOIN_REQUEST_ACCEPTED'::character varying, 'GROUP_JOIN_REQUEST_REJECTED'::character varying, 'GROUP_MEMBER_REMOVED'::character varying])::text[])))
);

CREATE TABLE IF NOT EXISTS public."matching_configs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "criterion" varchar(20) NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    "weight" double precision NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "matching_configs_criterion_check" CHECK (((criterion)::text = ANY ((ARRAY['COURSE'::character varying, 'AVAILABILITY'::character varying, 'STUDY_MODE'::character varying, 'STUDY_GOAL'::character varying, 'GROUP_SIZE'::character varying])::text[]))),
    CONSTRAINT "uk2qjp2v8hbvpiltp7w32a7o9b1" UNIQUE (criterion)
);

CREATE TABLE IF NOT EXISTS public."matching_strategy_settings" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "active_strategy" varchar(20) NOT NULL,
    "updated_at" timestamp without time zone NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "matching_strategy_settings_active_strategy_check" CHECK (((active_strategy)::text = ANY ((ARRAY['BALANCED'::character varying, 'AVAILABILITY_FIRST'::character varying, 'COURSE_FIRST'::character varying])::text[])))
);
