-- Shared state is durable; presence is an expiring browser-tab lease.
CREATE TABLE IF NOT EXISTS study_rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_group_id bigint NOT NULL UNIQUE REFERENCES study_groups(id) ON DELETE CASCADE,
    host_id bigint REFERENCES students(id) ON DELETE SET NULL,
    co_host_id bigint REFERENCES students(id) ON DELETE SET NULL,
    version bigint NOT NULL DEFAULT 0,
    focus_minutes integer NOT NULL CHECK (focus_minutes > 0),
    break_minutes integer NOT NULL CHECK (break_minutes > 0),
    participant_limit integer NOT NULL CHECK (participant_limit > 0),
    phase varchar(20) NOT NULL CHECK (phase IN ('FOCUS','BREAK')),
    timer_status varchar(20) NOT NULL CHECK (timer_status IN ('IDLE','RUNNING','PAUSED')),
    remaining_millis bigint NOT NULL CHECK (remaining_millis > 0),
    timer_anchor timestamptz,
    audio_preset varchar(20) NOT NULL CHECK (audio_preset IN ('CALM_MUSIC','RAIN','WHITE_NOISE','CAFE')),
    audio_playing boolean NOT NULL DEFAULT false,
    CHECK ((timer_status = 'RUNNING') = (timer_anchor IS NOT NULL)),
    CHECK (host_id IS NULL OR co_host_id IS NULL OR host_id <> co_host_id)
);

CREATE TABLE IF NOT EXISTS room_presences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_room_id bigint NOT NULL REFERENCES study_rooms(id) ON DELETE CASCADE,
    student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    client_id uuid NOT NULL,
    expires_at timestamptz NOT NULL,
    observed_at timestamptz NOT NULL,
    presence varchar(20) NOT NULL CHECK (presence IN ('PRESENT','FOCUS','BREAK')),
    UNIQUE (study_room_id, student_id, client_id),
    CHECK (expires_at > observed_at)
);
CREATE INDEX IF NOT EXISTS room_presence_expiry_idx ON room_presences(study_room_id, expires_at);
CREATE INDEX IF NOT EXISTS room_presence_student_idx ON room_presences(student_id);

ALTER TABLE study_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE room_presences ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE study_rooms, room_presences FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE study_rooms_id_seq, room_presences_id_seq FROM PUBLIC, anon, authenticated;
