package com.studybuddy.notification;

public enum NotificationType {
    MATCH_REQUEST_RECEIVED,
    MATCH_REQUEST_ACCEPTED,
    MATCH_REQUEST_DECLINED,
    CONNECTION_ENDED,
    GROUP_JOIN_REQUEST_RECEIVED,
    GROUP_JOIN_REQUEST_ACCEPTED,
    GROUP_JOIN_REQUEST_REJECTED,
    GROUP_MEMBER_REMOVED
}
